server:
  port: 8081
  error:
    include-message: always
#Configuracion de spring
spring:
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://lallah.db.elephantsql.com:5432/ylmbqwdm?socketTimeout=3
    username: ylmbqwdm
    password: 8l6w2Ra1v65blnlsHRdShW91xS3S3jLe
    driverClassName: org.postgresql.Driver